# Generated by Django 5.2 on 2025-05-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_feepayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feepayment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Fee Payment', 'verbose_name_plural': 'Fee Payments'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'Student Profile', 'verbose_name_plural': 'Student Profiles'},
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_standard',
            field=models.CharField(choices=[('all', 'Everyone'), ('1', 'Standard 1'), ('2', 'Standard 2'), ('3', 'Standard 3'), ('4', 'Standard 4'), ('5', 'Standard 5'), ('6', 'Standard 6'), ('7', 'Standard 7'), ('8', 'Standard 8'), ('9', 'Standard 9'), ('10', 'Standard 10'), ('11', 'Standard 11'), ('12', 'Standard 12')], default='all', max_length=3),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
