# Generated by Django 5.2 on 2025-05-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_feepayment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='stream',
            field=models.CharField(blank=True, choices=[('commerce', 'Commerce')], max_length=20, null=True),
        ),
    ]
