# Generated by Django 5.2 on 2025-05-25 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_studentprofile_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('bank', 'Bank Transfer')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='users.studentprofile'),
        ),
    ]
